/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package softnutri;

/**
 *
 * @author Carolina
 */
public class TelaDetalhesConsulta extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaDetalhesConsulta.class.getName());
    private Consulta consulta;
    private TelaInicial telaInicial;
    /**
     * Creates new form TelaDetalhesConsulta
     */
    public TelaDetalhesConsulta() {
        initComponents();
    }
    public void setConsulta(Consulta consulta) {
        this.consulta = consulta;
        chckConsultaRealizada.setSelected(consulta.getJa_realizado());
        
        
    if (consulta.getJa_realizado()) {
        chckConsultaRealizada.setEnabled(false);
        txtObservacao.setText(consulta.getObservacoes());
        btnFinalizar.setVisible(false);
    } else {
        chckConsultaRealizada.setSelected(false);
        chckConsultaRealizada.setEnabled(true);
        txtObservacao.setText("");
        btnFinalizar.setVisible(true);
    }
        
        
    }
    public void setTelaInicial(TelaInicial telaInicial) {
    this.telaInicial = telaInicial;
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblReceitasobs = new javax.swing.JLabel();
        btnFinalizar = new javax.swing.JButton();
        chckConsultaRealizada = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObservacao = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblTitulo.setText("Detalhes da Consulta");

        lblReceitasobs.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblReceitasobs.setText("Receita e observações:");

        btnFinalizar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnFinalizar.setText("Finalizar");
        btnFinalizar.addActionListener(this::btnFinalizarActionPerformed);

        chckConsultaRealizada.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        chckConsultaRealizada.setForeground(new java.awt.Color(102, 102, 102));
        chckConsultaRealizada.setText("Consulta Realizada");

        txtObservacao.setColumns(20);
        txtObservacao.setRows(5);
        txtObservacao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setViewportView(txtObservacao);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(btnFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(chckConsultaRealizada, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblReceitasobs, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chckConsultaRealizada, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblReceitasobs, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(btnFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed

        String observacoes = txtObservacao.getText().trim();

if (observacoes.isEmpty()) {
    javax.swing.JOptionPane.showMessageDialog(
        this,
        "Informe a receita e/ou observações antes de finalizar."
    );
    return;
}

try {
    if (consulta == null) {
        javax.swing.JOptionPane.showMessageDialog(
            this,
            "Nenhuma consulta foi selecionada."
        );
        return;
    }

    consulta.setObservacoes(observacoes);
    consulta.setJa_realizado(true);

    javax.swing.JOptionPane.showMessageDialog(
        this,
        "Consulta finalizada com sucesso!"
    );
telaInicial.atualizarTabela();
    this.dispose();

} catch (Exception e) {
    javax.swing.JOptionPane.showMessageDialog(
        this,
        "Erro ao finalizar a consulta."
    );
}        // TODO add your handling code here:
    }//GEN-LAST:event_btnFinalizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaDetalhesConsulta().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JCheckBox chckConsultaRealizada;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblReceitasobs;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextArea txtObservacao;
    // End of variables declaration//GEN-END:variables
}
